# Generated by Django 4.1.3 on 2023-05-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consultas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=280, verbose_name="Consult Text")),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "urgencia",
                    models.CharField(
                        max_length=280, verbose_name="Retorno sobre urgência"
                    ),
                ),
                (
                    "valores",
                    models.CharField(
                        max_length=280, verbose_name="Retorno sobre Valores"
                    ),
                ),
                (
                    "pessoal",
                    models.CharField(
                        max_length=280,
                        verbose_name="Retorno sobre Informações pessoais",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        max_length=280, verbose_name="Retorno sobre links"
                    ),
                ),
            ],
        ),
    ]
